FROM php:8.3.2-fpm-bookworm

RUN apt-get update && apt-get install -y && apt-get install -y --no-install-recommends \
      git \
      zlib1g-dev \
      libxml2-dev \
      libzip-dev

RUN docker-php-ext-install \
      zip \
      intl \
      mysqli \
      pdo pdo_mysql

RUN curl -sS http://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

COPY src/ /var/www
WORKDIR /var/www