version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile-nginx
    volumes:
      - ./app/:/var/www
    ports:
      - 8001:80
    depends_on:
      - php
    networks:
      - symfony

  php:
    container_name: php
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile-php
    environment:
      APP_ENV: dev
    volumes:
      - ./app/:/var/www/
    networks:
      - symfony
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - symfony
    depends_on:
      - mysql

networks:
  symfony:

volumes:
  db-vol: